apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: arielaz4/expiration  # Replace with your actual Docker image
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "nats://nats-srv:4222"  # Replace with your NATS server URL
            - name: NATS_CLUSTER_ID
              value: ticketing  # Replace with your NATS cluster ID
            - name: REDIS_HOST
              value: expiration-redis-srv  # Replace with your Redis service name
