apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-redis-mongo-depl
  template:
    metadata:
      labels:
        app: expiration-redis-mongo-depl
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-srv
spec:
  selector:
    app: expiration-redis-mongo-depl  # Update to match your Deployment selector
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
